apiVersion: apps/v1
kind: Deployment
metadata:
  name: firedog-deployment
  labels:
    bot: firedog
spec:
  selector:
    matchLabels:
      bot: firedog
  template:
    metadata:
      labels:
        bot: firedog
    spec:
      containers:
      - name: bot
        image: ghcr.io/tuna2134/firedog
        env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: bot-secret
              key: token
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: bot-secret
              key: db-port
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: bot-secret
              key: db-host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: bot-secret
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bot-secret
              key: db-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: bot-secret
              key: db-name
        - name: OPENAI_APIKEY
          valueFrom:
            secretKeyRef:
              name: bot-secret
              key: openai-apikey
